services:
  - type: web
    name: rovello-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:5000 backend.server:app